"""create jobs table

Revision ID: 80a4b5684683
Revises: 
Create Date: 2023-04-15 05:42:29.021389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a4b5684683'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('experience_level', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('qualify_for', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('sent', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
